name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn clean package -DskipTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=lumia-beanstalk_project-2
            -Dsonar.organization=lumia-beanstalk
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
            -Dsonar.branch.name=master
                 
      
  build:
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' 
      
      - name: Set up Maven 3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.0'
      
      - name: Build artifact
        run: mvn clean package -DskipTests


      - name: Extract WAR
        run: |
          mkdir extracted
          unzip target/lumiatech-v1.war -d extracted

      # - name: Trivy Scan Extracted WAR
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'
      #     scan-ref: 'extracted'
      #     format: 'table'
      #     exit-code: '1'
      #     severity: 'HIGH,CRITICAL'

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Change to your region
          APPLICATION_NAME: 'lumiatech-tomcat-app-v2'
          ENVIRONMENT_NAME: 'lumiatech-tomcat-app-env-v2'
        run: |
          echo "Deploying to Elastic Beanstalk..."
          # Create a ZIP file from the WAR file
          cp target/lumiatech-v1.war ROOT.war
          zip -r ROOT.zip ROOT.war
          aws s3 cp ROOT.zip s3://ndzenyuy-test-bucket/ROOT.zip
          
          # Deploy the ZIP file using the AWS CLI
          aws elasticbeanstalk create-application-version --application $APPLICATION_NAME --version-label $GITHUB_RUN_NUMBER --source-bundle S3Bucket=ndzenyuy-test-bucket,S3Key=ROOT.zip
          aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_RUN_NUMBER

      
